# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True)),
                ('artist', models.CharField(max_length=127, null=True)),
                ('album', models.CharField(max_length=127, null=True)),
            ],
        ),
    ]
