# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_auto_20160311_2319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='musicmodel',
            unique_together=set([('title', 'artist')]),
        ),
    ]
