# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musics', '0006_auto_20160313_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmodel',
            name='users',
            field=models.ManyToManyField(related_name='musics', to=settings.AUTH_USER_MODEL),
        ),
    ]
